// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "bc9b04b6-8a08-4d7b-b51b-e3b4a246cb68");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1664469512);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1664469511);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{fdbca150-b109-4078-ba43-7193648bb1d0}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1664469509);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{00b55fe5-128f-4552-a29c-aee6f084f726}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1664469511);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1664469511838");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1664491111838");
user_pref("browser.search.region", "CL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1664469511");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220928105009");
user_pref("browser.startup.homepage_override.mstone", "105.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1664469510);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1664469511758");
user_pref("distribution.iniFile.exists.appversion", "105.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.nixos.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CL");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "1fbd084a8da648a380647768ced72258");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220928105009");
user_pref("extensions.lastAppVersion", "105.0.1");
user_pref("extensions.lastPlatformVersion", "105.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"830f0198-22c9-420c-904c-fa9886a5cb07\",\"pictureinpicture@mozilla.org\":\"3a883a87-3b6f-432f-9f96-193c973b2581\",\"screenshots@mozilla.org\":\"2996ea25-17a2-4b74-b482-563e29e4df55\",\"webcompat-reporter@mozilla.org\":\"af54116b-c9a5-418f-b3c1-58ff28b25585\",\"webcompat@mozilla.org\":\"00ed0ca9-d7e6-4ceb-8389-f2acf266f716\",\"default-theme@mozilla.org\":\"d80c5063-b5c4-481d-948a-1b65ffe67e78\",\"addons-search-detection@mozilla.com\":\"5b92b8c3-fd9d-441f-befe-6705f16481b9\",\"google@search.mozilla.org\":\"8413e645-e144-486a-8120-3ca73d0f832b\",\"amazondotcom@search.mozilla.org\":\"6fd587e7-da57-4794-acd3-ff7e974a97bb\",\"wikipedia@search.mozilla.org\":\"c43c94eb-0588-404a-a88e-352e33be42cf\",\"bing@search.mozilla.org\":\"0ef52e0f-fc24-4d59-8970-8e89c2a87cec\",\"ddg@search.mozilla.org\":\"ae762432-2c31-4930-a3d5-25abe99864e9\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1664469511);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4da70339-60e2-4b48-92ed-a31126d88d65");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.cachedClientID", "770ebf04-b8a4-45bb-8c0a-e0f3143c1d0a");
user_pref("toolkit.telemetry.previousBuildID", "20220928105009");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
